version: "3.3"
services:
  rtsp_server:
    build: .
    restart: always
    container_name: rtsp
    volumes:
      - "/mnt/kareoke:/mnt/kareoke"
    environment:
      VIDEO_PATH: '/mnt/kareoke/video'
      KAREOKE_PATH: '/mnt/kareoke/Songs'
      HTTP_PORT: '8001'
      RTSP_PORT: '4586'
      PLAYLIST_SERVER_URL: 'http://kareoke-client:8080'
      PLACEHOLDER_VIDEO: '/mnt/kareoke/placeholder/discoball10.mp4'
    ports:
      - 4586:4586
      - 8001:8001